name: Quatt Test Automation

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main, develop]

jobs:
  automation-test:
    name: Run Automation Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20"
      - run: npm install
      - run: npm run test
